### ISSUE TITLE
PSSendGrid error when using the vault to retrieve the api key

### ISSUE THREAD

**Issue by akrofly** [Ba4bes/PSSendGrid#10]
When attempting to retrieve the API key via azure vault the following error shows up:

**{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}**

It does however work perfectly as long as the api key in a one liner and not retrieved from the vault and used in the invoke-restmethod -headers ........ 
Is retrieving the api key via the get-azkeyvaultsecret method not supported in this version or am I lacking to see my mistakes?

Kind regards.

**Comment by Ba4bes** [comment]
Hi,
Could you show me the (anonymized) PowerShell lines that you use to collect the token from the keyvault and pass it through? Then I can test to see if I can reproduce

**Comment by akrofly** [comment]
$Temp_key = Get-AzKeyVaultSecret -VaultName $VaultName -Name "TestSendGridAPIname"
$API_KEY =  $Temp_key.SecretValue  |  ConvertFrom-SecureString
$header = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$header.Add("Authorization", "Bearer " + $API_KEY)
$header.Add("Content-Type", "application/json")

**Comment by Ba4bes** [comment]
I have just tested the below code and it worked without issue

```PowerShell
$Temp_key = Get-AzKeyVaultSecret -VaultName $VaultName -Name "TestSendGridAPIname"
$API_KEY = $Temp_key.SecretValue | ConvertFrom-SecureString -AsPlainText
$MailParameters = @{
    FromAddress = "from@address.com"
    ToAddress   = "to@address.com"
    Subject     = "apiKeyTest"
    Token       = $API_KEY
    FromName    = fromName
    ToName      = toName
    Body        = "Example"
}
Send-PSSendGridMail @MailParameters -Verbose
```
So you don't have to create the header, PSSendGrid does that for you.
Could you test if this works for you?

**Comment by akrofly** [comment]
I am out of the office and will be testing as soon as I get back and give you feedback. Thank you for your effort so far. Have a nice weekend

**Comment by akrofly** [comment]
I ran the test, still receiving an error, does not seem to accept using the -AsPlainText, as you can see from the text bellow.

ConvertFrom-SecureString : A parameter cannot be found that matches parameter name 'AsPlainText'. 
At line:18 char:71 + ... _KEY = $Temp_key.SecretValue | ConvertFrom-SecureString -AsPlainText + ~~~~~~~~~~~~ + CategoryInfo : 
InvalidArgument: (:) [ConvertFrom-SecureString], ParameterBindingException + FullyQualifiedErrorId : 
NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromSecureStringCommand 


Send-PSSendGridMail : Cannot bind argument to parameter 'Token' because it is an empty string. 
At line:28 char:21 + Send-PSSendGridMail @MailParameters -Verbose + ~~~~~~~~~~~~~~~ + CategoryInfo : 
InvalidData: (:) [Send-PSSendGridMail], ParameterBindingValidationException + FullyQualifiedErrorId : 
ParameterArgumentValidationErrorEmptyStringNotAllowed,Send-PSSendGridMail 

System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'AsPlainText'.

**Comment by Ba4bes** [comment]
I'm sorry, -AsPlainText only works with Powershell 6+ and a runbook runs on PowerShell 5.1
If you still want to start with a secure string, you can use the following syntax

```PowerShell
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($Temp_key.SecretValue))
```

**Comment by akrofly** [comment]
Thank you.

**Comment by akrofly** [comment]
Thank you,
