### ISSUE TITLE
Empty attachments are populated with previous attachment data

### ISSUE THREAD

**Issue by Adhdmatt** [Ba4bes/PSSendGrid#12]
Currently, if I create an attachment array and add an attachment with data, followed by one with no data, both attachments end up being populated with data from attachment 1. 

It seems there may need to be a Clear-Variable at the end of your " if ($AttachmentPath)" statement, for the variable $Attachmentobject.

**Comment by Ba4bes** [comment]
Great suggestion! I think it is a good idea to clear all variables at the end of the function.
I am going to see if I can look into this next week.

**Comment by Ba4bes** [comment]
At the end of the cmdlet the new variables are now cleared
