### ISSUE TITLE
Invalid email address: user@domain.support

### ISSUE THREAD

**Issue by mmccollum2** [Ba4bes/PSSendGrid#14]
Hello!

Love the module you've put together.

https://github.com/Ba4bes/PSSendGrid/blob/master/PSSendGrid/PSSendGrid.psm1
Line 27
$EmailAddressRegex = '^([\w-.]+)@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.)|(([\w-]+.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(]?)$'
This email address regex checker doesn't support - domain.support as a valid domain.

For now i've just pulled the function from your module and removed the Regex checker. 

Thanks!

**Comment by Ba4bes** [comment]
You are right, this regex doesn't take care of the newer TLD's.

So I'm thinking of making use of the c# class for mailaddress [link](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress?view=net-6.0)

Some other inspiration: [link](https://stackoverflow.com/questions/48253743/powershell-to-validate-email-addresses)

**Comment by Ba4bes** [comment]
I have changed the mailcheck, it should now be able to handle for example domain.support
