### ISSUE TITLE
issue sending multiple emails in one script

### ISSUE THREAD

**Issue by jgriffiths014** [Ba4bes/PSSendGrid#15]
Hi,

I have a script that sends 2 distinctly different emails, both using hashtables. the first email sends successfully, but the second acts as if some(but not all) of the values are missing from the hashtable and fails to send. I've misplaced the actual error I'm getting, but does anyone have any experience in getting this to work? I've tried different names and the same name for the hashtables and just changing the values, but this doesn't seem to work either,

Thanks

**Comment by Ba4bes** [comment]
Hi @jgriffiths014 ,

Could you show an anonymized version of the relevant parts of your script here? That would give me a better understanding of what is going on.

**Comment by jgriffiths014** [comment]
Hi,

its basically 2 hastables with 2 send operations, hastables generated from a mix of static input and variables generated throughout the script:

`

$MailParams = @{
	ToAddress   = '<redacted>'
	FromAddress = 'noreply_usermanagement@<redacted>'
	Subject     = $ManagerSubject
	BodyAsHtml  = $ManagerEmailBody
	Token       = $sgToken
}
Send-PSSendGridMail @MailParams

$ITSubject = "User Offboarding for $user - Expiry Reminder"
$ITBody = @"
User %user has now been offboarded, please set a reminder for %expirydate to fully remove the account, shared mailbox & OneDrive.
	You will also need to check the user has been removed from %remaininggroups, these are likely AAD synced groups.
	
	Manager was %ManagerUserPrincipalName
"@

$ITBody = $ITBody.replace("%user",$user).replace("%expirydate",$expirydate).replace("$remaininggroups",$remaininggroups).replace("%ManagerUserPrincipalName",$manager.UserPrincipalName)

$MailParams = @{
	ToAddress   = 'itsupport@<redacted>'
	FromAddress = 'noreply_usermanagement@<redacted>'
	Subject     = $ITSubject
	Body        = $ITBody
	Token       = $sgToken
}
Send-PSSendGridMail $MailParams
`

**Comment by Ba4bes** [comment]
In the second cmdlet you use
`Send-PSSendGridMail $MailParams` 
instead of
`Send-PSSendGridMail @MailParams`

Could you replace the $ with a @ to see if that works as expected?

**Comment by jgriffiths014** [comment]
omg, I feel so dumb. I've been staring at this for so long I obviously couldn't see the wood for the trees. Thank you for casting your eyes over it and I'm sorry for wasting your time :)

**Comment by Ba4bes** [comment]
No problem, no time wasted at all! Glad I could help :)
