### ISSUE TITLE
Handling multiple attachments

### ISSUE THREAD

**Issue by k00laidIT** [Ba4bes/PSSendGrid#2]
Thank you for putting this module out there! I'm trying to figure out how to attach multiple files with the AtttachmentPath parameter. I've tried = ".\file1.txt", ".\file2.txt", = ".\file1.txt", ".\file2.txt", and neither work. Is there a way to do this?

**Comment by Ba4bes** [comment]
Hi @k00laidIT ,
excuse me for the late reply, I had missed the mention for this issue.

At this point it is not possible to add multiple attachments. 
I am going to look into adding this functionality.

**Comment by Ba4bes** [comment]
I have just added version 0.2.0 to the gallery. This version adds the option for multiple attachments.

Don't forget to run ``` Update-Module PSSendGrid```

You can use it like this:

```PowerShell
$Parameters = @{
    AttachmentPath        = @(
        "c:\file1.jpg"
        "c:\file2.jpg"
    )
    BodyAsHTML            = '<h1>MetHTML</h1><img src="cid:example"><img src="cid:example2">'
    FromName              = Example9
    AttachmentID          = @(
        "example"
        "example2"
    )
    AttachmentDisposition = inline
    ToName                = Example0
    FromAddress           = "from@domain.com"
    ToAddress             = "to@domain.com"
    Subject               = Test with double inline attachment jpg
    Token                 = "TOKEN"
}

Send-PSSendGridMail @Parameters
```

I will close this issue, please reopen if you find problems with this functionality or still have questions.
Thank you for the suggestion!
