### ISSUE TITLE
Having issue in multiple ToAddress 

### ISSUE THREAD

**Issue by lomeshparmar** [Ba4bes/PSSendGrid#3]
Note: I've Used proper working email id in actual script.
**### Script :** 

$Receivers = @{
    "receiver one" = "lomesh.parmar@domain.com"
    "receiver two" = "emialid2@domain.com"
}

$Parameters = @{
    FromAddress = "TestSendGrid@domain.com"
    FromName    = "TestSendGrid_Name"
    ToAddress   = "lomesh.parmar@domain.com"
    ToName      = "Vagaro"
    Subject     = "SendGrid example"
    Body        = "This is an Testing email"
    Token       = "tokenkey"
}

Foreach ($Receiver in $Receivers.GetEnumerator()) {
    $Parameters.ToName = $Receiver.name
    $MailParameters.ToAddress = $Receiver.value
    Send-PSSendGridMail $MailParameters

}

**Error:**

The property 'ToAddress' cannot be found on this object. Verify that the property exists and can be set.
At line:22 char:5
+     $MailParameters.ToAddress = $Receiver.value
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Send-PSSendGridMail : Cannot validate argument on parameter 'ToAddress'. The argument "" does not match the 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" 
pattern. Supply an argument that matches 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" and 
try the command again.
At line:23 char:25
+     Send-PSSendGridMail $MailParameters
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-PSSendGridMail], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Send-PSSendGridMail
 
The property 'ToAddress' cannot be found on this object. Verify that the property exists and can be set.
At line:22 char:5
+     $MailParameters.ToAddress = $Receiver.value
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Send-PSSendGridMail : Cannot validate argument on parameter 'ToAddress'. The argument "" does not match the 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" 
pattern. Supply an argument that matches 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" and 
try the command again.
At line:23 char:25
+     Send-PSSendGridMail $MailParameters
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-PSSendGridMail], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Send-PSSendGridMail

**Comment by Ba4bes** [comment]
Hi @lomeshparmar . My apologies for the late reply, I had missed the mention for this issue.

In your script, you are using 
```Send-PSSendGridMail $MailParameters```
This should be replaced with 
```Send-PSSendGridMail @MailParameters```
Does that solve the issue?

**Comment by lomeshparmar** [comment]
@Ba4bes 
The property 'ToAddress' cannot be found on this object. Verify that the property exists and can be set.
At D:\Scripts\Functions\Untitled2.ps1:22 char:5
+     $MailParameters.ToAddress = $Receiver.value
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Send-PSSendGridMail : Cannot validate argument on parameter 'ToAddress'. The argument "" does not match the 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" pattern. Supply an 
argument that matches 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" and try the command 
again.
At D:\Scripts\Functions\Untitled2.ps1:23 char:25
+     Send-PSSendGridMail @MailParameters
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-PSSendGridMail], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Send-PSSendGridMail
 
The property 'ToAddress' cannot be found on this object. Verify that the property exists and can be set.
At D:\Scripts\Functions\Untitled2.ps1:22 char:5
+     $MailParameters.ToAddress = $Receiver.value
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Send-PSSendGridMail : Cannot validate argument on parameter 'ToAddress'. The argument "" does not match the 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" pattern. Supply an 
argument that matches 
"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$" and try the command 
again.
At D:\Scripts\Functions\Untitled2.ps1:23 char:25
+     Send-PSSendGridMail @MailParameters
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-PSSendGridMail], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Send-PSSendGridMail

**Comment by Ba4bes** [comment]
I tested the cmdlets but I cannot reproduce the error.

It seems that the $Parameters-object does not contain a ToAddress property, so the forloop at the end is not able to add it to the object.
Could you try to get an output of $Parameters before running the last loop to see if ToAddress is added? When you run $Parameters.ToAddress, the output should be "lomesh.parmar@domain.com"

**Comment by lomeshparmar** [comment]
$Parameters

Name                           Value                                                                                        
----                           -----                                                                                        
Body                           This is an Testing email                                                                     
FromAddress                    TestSendGrid@domain.com                                                                      
ToAddress                      lomesh.parmar@domain.com                                                                     
ToName                         Domain                                                                                       
Token                          SG.d3-PxpaaaRvQl6Q6HdHddpk6ZIg.7vJMKr7LlaBWULoeUvSc5KwvIIJdVynJ6MDzJb6vkSE                        
Subject                        SendGrid example                                                                             
FromName                       TestSendGrid_Name

**Comment by Ba4bes** [comment]
@lomeshparmar  you had posted your SendGrid token. I have removed it, but please remove that token from your SendGrid account to prevent abuse. 

This does look like expected. What version of PowerShell are you using?

**Comment by lomeshparmar** [comment]
@Ba4bes  Below Version
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.19041.610                                                                                
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.19041.610                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1

**Comment by Ba4bes** [comment]
I was able to reproduce and found the issue, there was an error in the example.
The variable $Mailparameters should be changed to $Parameters.

So the new code would be:
```PowerShell
$Receivers = @{
    "receiver one" = "lomesh.parmar@domain.com"
    "receiver two" = "emialid2@domain.com"
}

$Parameters = @{
    FromAddress = "TestSendGrid@domain.com"
    FromName = "TestSendGrid_Name"
    ToAddress = "lomesh.parmar@domain.com"
    ToName = "Vagaro"
    Subject = "SendGrid example"
    Body = "This is an Testing email"
    Token = "tokenkey"
}

Foreach ($Receiver in $Receivers.GetEnumerator()) {
    $Parameters.ToName = $Receiver.name
    $Parameters.ToAddress = $Receiver.value
    Send-PSSendGridMail @Parameters
}
```

This should work, I have changed the code in my blog post.
Can you please confirm if this fixes the issue?

**Comment by lomeshparmar** [comment]
> I was able to reproduce and found the issue, there was an error in the example.
> The variable $Mailparameters should be changed to $Parameters.
> 
> So the new code would be:
> 
> ```powershell
> $Receivers = @{
>     "receiver one" = "lomesh.parmar@domain.com"
>     "receiver two" = "emialid2@domain.com"
> }
> 
> $Parameters = @{
>     FromAddress = "TestSendGrid@domain.com"
>     FromName = "TestSendGrid_Name"
>     ToAddress = "lomesh.parmar@domain.com"
>     ToName = "Vagaro"
>     Subject = "SendGrid example"
>     Body = "This is an Testing email"
>     Token = "tokenkey"
> }
> 
> Foreach ($Receiver in $Receivers.GetEnumerator()) {
>     $Parameters.ToName = $Receiver.name
>     $Parameters.ToAddress = $Receiver.value
>     Send-PSSendGridMail @Parameters
> }
> ```
> 
> This should work, I have changed the code in my blog post.
> Can you please confirm if this fixes the issue?

@Ba4bes  

Thanks for the Quick Responses. YES Now It's Working !!
Thank You
