### ISSUE TITLE
How to attach csv file as attachment

### ISSUE THREAD

**Issue by jojireddyv** [Ba4bes/PSSendGrid#5]
Following is the script sends CSV as attachment but the data shows on single row.
Can you help me to get this fix.

Function SendGridMailWithAttachment {
    param (
        [cmdletbinding()]
        [parameter()] [string]$ToAddress,
        [parameter()] [string]$FromAddress,
        [parameter()] [string]$Subject,
        [parameter()] [string]$Body,
        [parameter()] [string]$APIKey,
        [parameter()] [string]$FileName,
        [parameter()] [string]$FileNameWithFilePath,
        [parameter()] [string]$AttachementType
          )
    #Convert File to Base64
        $FileContent = get-content $FileNameWithFilePath
        $ConvertToBytes = [System.Text.Encoding]::UTF8.GetBytes($FileContent)
        $EncodedFile = [System.Convert]::ToBase64String($ConvertToBytes)
    # Body with attachement for SendGrid
        $SendGridBody = @{
        "personalizations" = @( @{ 
              "to"= @( @{ "email" = $ToAddress } )
              "subject" = $Subject
                        } ) 
              "content"= @( @{
                          "type" = "text/html"
                          "value" = $Body
                             } )
              "from"  = @{ "email" = $FromAddress }
              "attachments" = @( @{
                                        "content"=$EncodedFile
                                        "filename"=$FileName
                                        "type"= $AttachementType
                                        "disposition"="attachment"
                                        } )
} 
       $BodyJson = $SendGridBody | ConvertTo-Json -Depth 4
    #Header for SendGrid API
        $Header = @{ "authorization" = "Bearer $APIKey" }
    #Send the email through SendGrid API
        $fnParameters = @{
            Method      = "POST"
            Uri         = "https://api.sendgrid.com/v3/mail/send"
            Headers     = $Header
            ContentType = "application/json"
            Body        = $BodyJson
            }
    Invoke-RestMethod @fnParameters
  } 

$Parameters = @{
    ToAddress   = ""
    FromAddress = ""
    Subject     = "Azure Inventory Report"
    Body        = "Please find the attachement."
    APIKey      = ""
    FileName = $csvfilename
    FileNameWithFilePath = $VMReportCsv
    AttachementType ="csv"
}
SendGridMailWithAttachment @Parameters

**Comment by Ba4bes** [comment]
When I use Send-PSSendGridMail from the module in this repository, I can send a csv without issues.
Can you try if that works? Find [this blogpost](https://4bes.nl/2020/07/26/pssendgrid-send-email-from-powershell-with-sendgrid/) for instructions on how to use the cmdlet.

**Comment by jojireddyv** [comment]
I made below change its working perfect now.
$FileContent = get-content -raw -path $FileNameWithFilePath
