### ISSUE TITLE
Cannot send mail with accented characters

### ISSUE THREAD

**Issue by jimthurston** [Ba4bes/PSSendGrid#6]
Hi, is there a way to specify my subject and body as Unicode with this module?  When sending an email with a subject line containing an accented character, I receive an 'Unsupported Media Type' exception.  Thanks!

**Comment by Ba4bes** [comment]
I have reproduced this, the encoding has issues with special characters.
I'm doing some research to see if I can make it possible to send the special characters anyway. If it can't be done I will replace them like you did. Thank you for letting me know about this issue!

**Comment by Ba4bes** [comment]
I have used a shorter function to replace the diacritics for all fields that are passed to Sendgrid.
Would have preferred to be able to send them with the accents, but I haven't been able to find a way to do that.
The error should be gone with the newest version, which I have just pushed to the PowerShell gallery. You can update by using  ```Update-Module PSSendGrid```
Thank you for your feedback!

**Comment by jimthurston** [comment]
Thanks, this is now working for me as you've indicated.
