### ISSUE TITLE
ToName and FromName are optional for sendGrid calls.

### ISSUE THREAD

**Issue by alexhatcher** [Ba4bes/PSSendGrid#7]
When you only have an email address, you can get around the issue with putting the email in the ToName as well.

but if you could remove the requirements for both, that would be best.

**Comment by Ba4bes** [comment]
The toName and FromName are no longer mandatory. The new version has been pushed to the PowerShell gallery and can be installed with ```Update-Module PSSendGrid```
Thank you for your feedback!
