### ISSUE TITLE
send to multiples AND BCC OR CC included

### ISSUE THREAD

**Issue by alexhatcher** [Ba4bes/PSSendGrid#9]
i was reviewing SendGrid's documentation for multiples.
https://sendgrid.com/docs/for-developers/sending-email/personalizations/#sending-a-single-email-to-a-single-recipient-with-a-cc-and-a-bcc

and while your loop solution works,  there is no capacity for CC or BCC.

**Comment by Ba4bes** [comment]
You are right, this is still something for my todo list. Also I want to make it possible to send to multiples without the loop. I'll see when I can find time for this one.

Thank you for bringing it up

**Comment by gioce90** [comment]
This is a must-have feature :)

**Comment by Ba4bes** [comment]
I've started working on this, hope to release somewhere this week or next week!

**Comment by Ba4bes** [comment]
And the new version has been released to the gallery.

There is now support to send to multiple To-Addresses, multiple CC-addresses and multiple BCC-addresses.

You can get the newest version with
``` PowerShell
Update-Module PSSendgrid
```

Thank you for the suggestion and please let me know if you have any issues!
